services:
  - name: web
    instance_count: 4
    routes:
      - path: /
    git:
      repo: "https://github.com/syahruromadona/jemah.git"
      branch: master
    envs:
    - key: OPENAI_API_KEY
      scope: BUILD_TIME